name: flutter_material_pickers_example
description: A Flutter project that demonstrated the use of the flutter_material_pickers package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_material_pickers:
    path: ../
  adaptive_theme: ^3.6.0
  intl: ^0.19.0
  file_picker: ^8.1.5

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
