name: flutter_material_pickers_example
description: A Flutter project that demonstrated the use of the flutter_material_pickers package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_material_pickers:
    path: ../
  adaptive_theme: ^2.3.1
  intl: ^0.17.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
