name: flutter_material_pickers
description: A flutter package for easily and consistently showing material themed picker dialogs.
version: 1.5.3
homepage: https://github.com/codegrue/flutter_material_pickers

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.3.4
  intl: ^0.16.0
  meta: ^1.1.6
  file_picker_cross: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
  uses-material-design: true
