name: flutter_material_pickers
description: A flutter package for easily and consistently showing material themed picker dialogs.
version: 3.7.1
homepage: https://github.com/codegrue/flutter_material_pickers
issue_tracker: https://github.com/codegrue/flutter_material_pickers/issues

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  intl: ^0.19.0
  file_picker: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  uses-material-design: true
